"""add rehearsal duration column

Revision ID: 2ccd15da92a7
Revises: 2d7f0f0f5927
Create Date: 2024-05-05 18:06:27.905523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccd15da92a7'
down_revision: Union[str, None] = '2d7f0f0f5927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lz_rehearsals', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lz_rehearsals', 'duration')
    # ### end Alembic commands ###
