"""create post and rehearsal tables

Revision ID: 2d7f0f0f5927
Revises: 7abada8b6002
Create Date: 2024-05-05 16:42:11.871537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7f0f0f5927'
down_revision: Union[str, None] = '7abada8b6002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lz_blocks',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banned_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('banned_till', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['lz_users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('lz_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('likes', sa.String(), nullable=False),
    sa.Column('dislikes', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('edited_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['lz_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lz_posts_id'), 'lz_posts', ['id'], unique=False)
    op.create_table('lz_rehearsals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('band_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['lz_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lz_rehearsals_id'), 'lz_rehearsals', ['id'], unique=False)
    op.create_table('lz_post_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('band_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['lz_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lz_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lz_post_comments_id'), 'lz_post_comments', ['id'], unique=False)
    op.create_table('lz_rehearsal_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rehearsal_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('band_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rehearsal_id'], ['lz_rehearsals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lz_rehearsal_participants_id'), 'lz_rehearsal_participants', ['id'], unique=False)
    op.add_column('lz_users', sa.Column('penalty_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO public.lz_permissions(description, permission_key) "
        "VALUES ('allow reading user entities', 'user_read'),"
        " ('allow updating user entities', 'user_update'),"
        " ('allow reading role entities', 'role_read'),"
        " ('allow editing role entities', 'role_update');"
    )
    # create superuser
    op.execute(
        "INSERT INTO public.lz_users(username, email, full_name, hashed_password,"
        " penalty_points, is_superadmin, created_on, edited_on)"
        " VALUES ('superadmin', 'su@iot.com', 'Head Admin',"
        " '$2b$12$x3VLmHbAYcJ9bYcTqtVWTO3iBgBbA0tFlHbyHnYmILRMc4yzAUxGK', '0',"
        " 'True', '2004-10-19 10:23:54', '2004-10-19 10:23:54');"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lz_users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('lz_users', 'penalty_points')
    op.drop_index(op.f('ix_lz_rehearsal_participants_id'), table_name='lz_rehearsal_participants')
    op.drop_table('lz_rehearsal_participants')
    op.drop_index(op.f('ix_lz_post_comments_id'), table_name='lz_post_comments')
    op.drop_table('lz_post_comments')
    op.drop_index(op.f('ix_lz_rehearsals_id'), table_name='lz_rehearsals')
    op.drop_table('lz_rehearsals')
    op.drop_index(op.f('ix_lz_posts_id'), table_name='lz_posts')
    op.drop_table('lz_posts')
    op.drop_table('lz_blocks')
    # ### end Alembic commands ###
