"""create all tables

Revision ID: 7abada8b6002
Revises: 
Create Date: 2024-04-28 17:26:02.120665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abada8b6002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lz_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('permission_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_key')
    )
    op.create_index(op.f('ix_lz_permissions_id'), 'lz_permissions', ['id'], unique=False)
    op.create_table('lz_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lz_roles_id'), 'lz_roles', ['id'], unique=False)
    op.create_table('lz_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('edited_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_lz_users_id'), 'lz_users', ['id'], unique=False)
    op.create_index(op.f('ix_lz_users_username'), 'lz_users', ['username'], unique=True)
    op.create_table('lz_permission_in_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['lz_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['lz_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('lz_sessions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['lz_users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('lz_user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['lz_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lz_users.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO public.lz_permissions(description, permission_key) "
        "VALUES ('allow reading user entities', 'user_read'),"
        " ('allow updating user entities', 'user_update'),"
        " ('allow reading role entities', 'role_read'),"
        " ('allow editing role entities', 'role_update');"
    )
    # create superuser
    op.execute(
        "INSERT INTO public.lz_users(username, email, full_name, hashed_password,"
        " is_active, is_superadmin, created_on, edited_on)"
        " VALUES ('superadmin', 'su@iot.com', 'Head Admin',"
        " '$2b$12$x3VLmHbAYcJ9bYcTqtVWTO3iBgBbA0tFlHbyHnYmILRMc4yzAUxGK', 'True',"
        " 'True', '2004-10-19 10:23:54', '2004-10-19 10:23:54');"
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lz_user_roles')
    op.drop_table('lz_sessions')
    op.drop_table('lz_permission_in_role')
    op.drop_index(op.f('ix_lz_users_username'), table_name='lz_users')
    op.drop_index(op.f('ix_lz_users_id'), table_name='lz_users')
    op.drop_table('lz_users')
    op.drop_index(op.f('ix_lz_roles_id'), table_name='lz_roles')
    op.drop_table('lz_roles')
    op.drop_index(op.f('ix_lz_permissions_id'), table_name='lz_permissions')
    op.drop_table('lz_permissions')
    # ### end Alembic commands ###
