"""fix postComment model

Revision ID: ce9c913490fc
Revises: 647600f4fc82
Create Date: 2024-05-28 12:24:15.292676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce9c913490fc'
down_revision: Union[str, None] = '647600f4fc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lz_post_comments', sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('lz_post_comments', 'band_name')
    op.drop_column('lz_post_comments', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lz_post_comments', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('lz_post_comments', sa.Column('band_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('lz_post_comments', 'created_on')
    # ### end Alembic commands ###
