"""delete mistaken columns

Revision ID: dc07554b1b00
Revises: 2ccd15da92a7
Create Date: 2024-05-06 21:27:04.555299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc07554b1b00'
down_revision: Union[str, None] = '2ccd15da92a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lz_rehearsal_participants', sa.Column('surname', sa.String(), nullable=False))
    op.drop_column('lz_rehearsal_participants', 'start_time')
    op.drop_column('lz_rehearsal_participants', 'band_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lz_rehearsal_participants', sa.Column('band_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lz_rehearsal_participants', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('lz_rehearsal_participants', 'surname')
    # ### end Alembic commands ###
